services:
 mongodb:
  image: mongo:6.0-rc-jammy
  container_name: mongodb
  ports:
    - "27087:27017"

  volumes:
    - mongodb:/data/db

  environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  networks:
   - backend
  restart: always

networks:
 backend:

 
volumes:
  mongodb: